settings:
  render_command:
    design: ../assets/yaml/rendercv_design.yaml
    locale: ../assets/yaml/rendercv_locale.yaml
    typst_path: ../assets/typ/jira_cv.typ
    pdf_path: ../assets/pdf/jira_cv.pdf
    markdown_path: ../assets/md/jira_cv.md
    html_path: ../assets/html/jira_cv.html
    png_path: ../assets/png/jira_cv.png
  bold_keywords: []
